### ISSUE TITLE
Transaction class doesn't have senderId field

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/java-wrapper-api#1]
The node requires the transactions JSON to have the senderId field. The `Transaction` class here doesn't have it nor does it automatically populate it. Thus the transactions generated are rejected by the node and it's impossible broadcast transactions.

**Comment by lystrosaurus** [comment]
+1

**Comment by vekexasia** [comment]
Hey @lystrosaurus just call `transaction.calculateID()` that shoudld be called from the `sign` method as you can see here.

https://github.com/RiseVision/java-wrapper-api/blob/81042e32724e2cf06f1ec4719d42df4d84c59011/src/main/java/rise/vision/Transaction.java#L119-L126

So it should be automatically populated.
